### ISSUE TITLE
Can only add through integration

### ISSUE THREAD

**Issue by safadig** [KaufHA/kauf-rgbww-bulbs#21]
wifi bulbs are on different subnet with no mDNS. I can add each bulb manually as Integration.  Ping enabled. Anyway I can manually add to ESPHome dashboard after they are added? For now, the Dashboard is empty.

**Comment by bkaufx** [comment]
I'd recommend removing from home assistant, adding to the esphome dashboard and reprogramming each device, then readding to home assistant.

Create a yaml file in the esphome config directory for each bulb. Copy in this yaml to each file:

```
substitutions:
  name: bedroom-lamp
  friendly_name: Bedroom Lamp

packages:
  kauf.rgbww: github://KaufHA/kauf-rgbww-bulbs/kauf-bulb.yaml

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
```

Rename each as desired. Add either a use_address or a manual_ip under each wifi section to point to the respective device per these directions: https://esphome.io/components/wifi.html

Then hit install in esphome and do it wirelessly.
