### ISSUE TITLE
4 Bulbs stopped responding after latest firmware update to 2023.9.3

### ISSUE THREAD

**Issue by Makr91** [KaufHA/kauf-rgbww-bulbs#42]
After updating ESPhome, I went through and updated all entities. I did not make any changes to the bulbs configurations.

I can't seem to revive these bulbs. I've only owned them about 10 months now. Is there a way to flash them with physical connectors?

These are specifically the A15's

The configs are as follows:

```
substitutions:
  disp_name: "office-ceiling-fan-light"
  friendly_name: Office Ceiling Fan Light
  update_time: 10s
  max_temp: "100.0"

  sub_red_pin:    GPIO4
  sub_green_pin:  GPIO12
  sub_blue_pin:   GPIO14
  sub_cw_pin:     GPIO5
  sub_ww_pin:     GPIO13

## Connection Configuration
wifi:
  domain: !secret domain
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password
    - ssid: !secret wifi_ssid2
      password: !secret wifi_password2
    - ssid: !secret wifi_ssid3
      password: !secret wifi_password3

  ap:
    ssid: "${friendly_name}"
    password: !secret fallback_password

logger:
  level: DEBUG

api:
  encryption:
      key: !secret api_key

ota:
  password: !secret ota_password

time:
  - platform: sntp
    id: sntp_time   
    timezone: !secret timezone
    servers:
      - !secret ntp_server1
      - !secret ntp_server2

captive_portal:

web_server:
  local: true

## Board Configuration
esphome:
  name: ${disp_name}
  name_add_mac_suffix: false

esp8266:
  board: esp01_1m
  restore_from_flash: true

## Sensor and Component Configuration
button:
  - platform: restart
    id: restart_button
    name: $friendly_name Restart Firmware
    entity_category: diagnostic

sensor:
  - platform: uptime
    name: $friendly_name Uptime
    update_interval: 60s
    entity_category: diagnostic
  - platform: wifi_signal
    name: "${friendly_name} WiFi Signal"
    update_interval: 60s
    entity_category: diagnostic

text_sensor:
  - platform: wifi_info
    ip_address:
      name: $friendly_name IP Address
      entity_category: diagnostic

output:
  - platform: esp8266_pwm
    pin: $sub_red_pin
    frequency: 200 Hz
    id: pwm_red
    max_power: .85
  - platform: esp8266_pwm
    pin: $sub_green_pin
    frequency: 200 Hz
    id: pwm_green
    max_power: .85
  - platform: esp8266_pwm
    pin: $sub_blue_pin
    frequency: 200 Hz
    id: pwm_blue
    max_power: .85
  - platform: esp8266_pwm
    pin: $sub_cw_pin
    frequency: 400 Hz
    id: pwm_cw
    max_power: .85
  - platform: esp8266_pwm
    pin: $sub_ww_pin
    frequency: 400 Hz
    id: pwm_ww
    max_power: .85

light:
  - platform: rgbww
    restore_mode: ALWAYS_ON
    name: "${friendly_name}"
    effects:
      - random:
      - strobe:
      - flicker:
      - pulse:
      - pulse:
          name: "Fast Pulse"
          transition_length: 0.5s
          update_interval: 0.5s
      - pulse:
          name: "Slow Pulse"
          transition_length: 1s
          update_interval: 2s
    red: pwm_red
    green: pwm_green
    blue: pwm_blue
    cold_white: pwm_cw
    warm_white: pwm_ww
    cold_white_color_temperature: 6500 K
    warm_white_color_temperature: 2700 K
    constant_brightness: true
    color_interlock: true
```
