### ISSUE TITLE
Can't update bulbs with ESPHome 2023.11.4 

### ISSUE THREAD

**Issue by mccmax1395** [KaufHA/kauf-rgbww-bulbs#48]
When I try to update my bulbs with ESPHome 2023.11.4, I get the following errror `ERROR Error binary size: Error: ESP does not have enough space to store OTA file. Please try flashing a minimal firmware (remove everything except ota)`

My configuration is pretty minimal expect for the kauf package.  Here's an example:
```
substitutions:
  name: "bedroom-bulb-1"
packages:
  Kauf.RGBWW: github://KaufHA/kauf-rgbww-bulbs/kauf-bulb.yaml
esphome:
  name: ${name}
  name_add_mac_suffix: false
api:
  encryption:
    key: REDACTED


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
```
