### ISSUE TITLE
Unable to update due to lack of space

### ISSUE THREAD

**Issue by mtgpcs** [KaufHA/kauf-rgbww-bulbs#49]
INFO Uploading /data/build/kauf-bulb-xxxxx/.pioenvs/kauf-bulb-xxxxxx/firmware.bin (606672 bytes)
INFO Compressed to 417949 bytes
ERROR Error binary size: Error: ESP does not have enough space to store OTA file. Please try flashing a minimal firmware (remove everything except ota)

The only workaround I found was to use the kauf-bulb-minimal.yaml then to change it back after and update it again. This was fine then the next ESPHome update same issue. 

This is happening across all my Kauf bulbs.

**Comment by bkaufx** [comment]
What do you have in the yaml besides the defaults?  This never used to be a problem for the bulbs so I'll have to take a look and see what changed from the ESPHome side.  You can always just take out the API encryption.

**Comment by mtgpcs** [comment]
substitutions:
  name: kauf-bulb-xxxxx
packages:
  Kauf.RGBWW: github://KaufHA/kauf-rgbww-bulbs/kauf-bulb.yaml
esphome:
  name: ${name}
  name_add_mac_suffix: false
api:
  encryption:
    key: 


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password


This is my whole yaml. What does taking out the encryption key do?

**Comment by SpencerDub** [comment]
I'm also having this issue. My YAML is also fairly minimal (a few things modified for privacy):

```
substitutions:
  name: spouses-bedside-light-2
  friendly_name: "Spouse's Bedside Light 2"

packages:
  Kauf.RGBWW: github://KaufHA/kauf-rgbww-bulbs/kauf-bulb.yaml

esphome:
  name: ${name}
  name_add_mac_suffix: false
  comment: The bulb in [Spouse]'s nightstand lamp that points away from the bed.

api:
  encryption:
    key: [encryption key]

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    # Set this to the IP of the ESP
    static_ip: XXX.XXX.XXX.XXX
    # Set this to the IP address of the router. Often ends with .1
    gateway: XXX.XXX.XXX.XXX
    # The subnet of the network. 255.255.255.0 works for most home networks.
    subnet: 255.255.255.0
```
