### ISSUE TITLE
Custom Power On State?

### ISSUE THREAD

**Issue by aeleus** [KaufHA/kauf-rgbww-bulbs#73]
I just added 4 BRF30 bulbs to Home Assistant. The Power On State options seem to be limited to Off, On - Bright White, or some version of the last value. Is there a way to configure them so that they always power on at, for example, 50% brightness and 2800K? 

Having them come at "last value" doesn't work because I have no control over what state they may be in when someone turns off the switch. Power on at Bright White is no good either.

The bulbs came with firmware version 1.873(f), and so far I have updated 2 of them to 1.93(u).

HA 2024.11.2 running in a container.
I am not running ESPHome Dashboard.
I have not configured the bulbs with any yaml files.

Thanks in advance.

**Comment by bkaufx** [comment]
Actually this feature was just added to ESPHome in the new update coming out tomorrow.  For now you'd have to add it to your own yaml.

Later on this week I'll try to get it working and post the yaml.

**Comment by aeleus** [comment]
FYI: I flashed one of the Kauf bulbs with the latest Tasmota 14.3.0. It seems Tasmota does not have the ability to configure a user-defined PowerOnState either. :-(

Here are the options for Tasmota:
PowerOnState	Control relay state after powering up the device.
0 / OFF = keep relay(s) OFF after power up
1 / ON = turn relay(s) ON after power up
2 / TOGGLE = toggle relay(s) from last saved state
3 = switch relay(s) to their last saved state (default)
4 = turn relay(s) ON and disable further relay control
5 = after a PulseTime period turn relay(s) ON (acts as inverted PulseTime mode)

**Comment by bkaufx** [comment]
For the yaml, here is what you have to add to the default.  Substitution section likely already exists so just add the restore mode substitution to that section.  Change values under initial_state to your liking.

```
substitutions:
  light_restore_mode: ALWAYS_ON


light:
  - id: !extend kauf_light
    initial_state:
      state: on
      brightness: 75%
      color_mode: color_temperature
      color_temperature: 2800K

      # color_mode: rgb
      # red: 100%
      # green: 0%
      # blue: 0%
```
